# -*- python -*-
import os
package = 'optimizers'
home = os.environ[package.upper() + 'ROOT']
#OptPP_dir = '/home/jchiang/data/OPT++2.1'
OptPP_dir = '/scratch/jchiang/OPT++2.1'
libraries = {'xml': None,
             'cfitsio': (os.path.join(os.environ['CFITSIO_DIR'], 'include'),
                         os.path.join(os.environ['CFITSIO_DIR'], 'lib')),
             'CLHEP': (os.path.join(os.environ['CLHEP_DIR'], '1.8.0.0',
                                    'include'),
                       os.path.join(os.environ['CLHEP_DIR'], '1.8.0.0','lib')),
             'f2c': None,
             'facilities': None,
             'xerces-c1_7_0': (os.path.join(os.environ['XMLEXT_DIR'],
                                            'include'),
                               os.path.join(os.environ['XMLEXT_DIR'], 'lib')),
             'g2c': ('',''),
             'opt-linux': (os.path.join(OptPP_dir, 'include'),
                           os.path.join(OptPP_dir, 'lib')),
             'newmat-linux': (os.path.join(OptPP_dir, 'newmat09'),
                              os.path.join(OptPP_dir, 'lib')),
             }

cflags = ' -DHAVE_OPT_PP'
Export(['package', 'home', 'libraries', 'cflags'])
SConscript('buildBase')
