# -*- python -*-
import os

class map(dict):
    def __init__(self):
        dict.__init__(self)
        self.ordered_keys = []
    def __setitem__(self, key, value):
        dict.__setitem__(self, key, value)
        self.ordered_keys.append(key)

package = 'optimizers'
home = os.environ[package.upper() + 'ROOT']
#OptPP_dir = '/home/jchiang/data/OPT++2.1'
#OptPP_dir = '/scratch/jchiang/OPT++2.1'

OptPP_dir = os.environ['OPTPP_DIR']

libraries = map()
libraries["xml"] = None
libraries["f2c"] = None
libraries["facilities"] = None
libraries["g2c"] = ('', '')

def externalLibrary(libname, version):
    libdir = os.path.join(os.environ['GLAST_EXT'], libname, version)
    return [os.path.join(libdir, 'include'), os.path.join(libdir, 'lib')]
    
libraries['cfitsio'] = externalLibrary('cfitsio', 'v2470')
libraries['CLHEP'] = externalLibrary('CLHEP', '1.8.0.0')
libraries['xerces-c'] = externalLibrary('xerces', '2.6.0')

libraries['opt-linux'] = (os.path.join(OptPP_dir, 'include'),
                          os.path.join(OptPP_dir, 'lib'))
libraries['newmat-linux'] = (os.path.join(OptPP_dir, 'newmat09'),
                             os.path.join(OptPP_dir, 'lib'))

cflags = ' -DHAVE_OPT_PP -g '
Export(['package', 'home', 'libraries', 'cflags'])
SConscript('buildBase')
